name: Publish MOU to PyPI

on:
  push:
    tags:
      - 'v*'
      - 'V*'
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - run: |
          python -m pip install --upgrade pip setuptools wheel build twine

      - run: python -m build

      - run: |
          pip install dist/*.whl
          python -c "import mou; print('MOU imported successfully!')"

  publish:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - run: |
          python -m pip install --upgrade pip setuptools wheel build twine

      - run: python -m build

      - uses: pypa/gh-action-pypi-publish@v1.6.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
