name: Publish MOU to PyPI

on:
  push:
    tags:
      - 'v*'
      - 'V*'
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Upgrade pip & install build tools
        run: |
          python -m pip install --upgrade pip setuptools wheel build twine

      - name: Build the package
        run: python -m build

      - name: Test local install
        run: |
          pip install dist/*.whl
          python -c "import mou; print('MOU imported successfully!')"

  publish:
    needs: build-and-test
    runs-on: ubuntu-latest
    # Always runs for tag push, release, or manual dispatch
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'release' || github.event_name == 'push' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Upgrade pip & install build tools
        run: |
          python -m pip install --upgrade pip setuptools wheel build twine

      - name: Build the package
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.6.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
